kyma-project/opentelemetry-collector-components

- CODEOWNERS
**Description**
Changes proposed in this pull request:
- Setup CODEOWNERS similar to telemetry-manager
**Related issue(s)**
> chore: Setup CODEOWNERS

- .github/workflows/build-and-test.yml
- cmd/otelkymacol/go.mod
- receiver/dummymetricsreceiver/config.go
**Description**
Changes proposed in this pull request:
- initial workflows for building, testing, linting
**Related issue(s)**
> chore: Add workflows

- .github/workflows/build-image.yaml
**Description**
Changes proposed in this pull request:
- ...
- ...
- ...
**Related issue(s)**
> chore: fix image builder job

- otel-collector/builder-config-release.yaml
**Description**
Changes proposed in this pull request:
- releases follow the X.Y.Z pattern not the vX.Y.Z pattern
**Related issue(s)**
> chore: Fix release tag pattern in build-config

- .reuse/dep5
- fixed copyright/license issue
-
> chore: Reuse compliance

- sec-scanners-config.yaml
- add configuration for whitesource scanning
-
> chore: Add sec-scanners-config

- .github/workflows/pr-code-checks.yml
- pr checks have been skipped as dependabot
-
> chore: Enable all actions for dependabot

- .github/dependabot.yml
- reduce dependabot gomod sections to one
-
> chore: Simplify dependabot Part II

- receiver/dummymetricsreceiver/config.go
- receiver/dummymetricsreceiver/config_test.go
- receiver/dummymetricsreceiver/metrics_receiver.go
- receiver/dummymetricsreceiver/testdata/config.yaml
- Handle all errors
- avoid race conditions
-
> fix: Unhandled errors and race conditions

- .reuse/dep5
- internal/k8sconfig/config.go
-  fix the broken reuse file
-
> fix: Fix reuse file

- .golangci.yaml
- Makefile
- Makefile.Common
- receiver/dummyreceiver/config.go
- receiver/dummyreceiver/config_test.go
- receiver/dummyreceiver/docs.go
- receiver/dummyreceiver/factory.go
- receiver/dummyreceiver/metrics_receiver.go
- receiver/singletonreceivercreator/config.go
- receiver/singletonreceivercreator/config_test.go
- receiver/singletonreceivercreator/factory.go
- receiver/singletonreceivercreator/factory_test.go
- receiver/singletonreceivercreator/go.mod
- receiver/singletonreceivercreator/leader_elector.go
- receiver/singletonreceivercreator/leader_elector_test.go
- receiver/singletonreceivercreator/receiver.go
- receiver/singletonreceivercreator/receiver_test.go
- receiver/singletonreceivercreator/runner.go
- receiver/singletonreceivercreator/runner_test.go
- add linter configuration similar to telemetry-manager
-
> chore: Add linter config

- sec-scanners-config.yaml
- Exclude generated files from whitesource scans
-
> chore: Exclude generated files from whitesource scans

- receiver/dummyreceiver/factory.go
- receiver/dummyreceiver/metrics_receiver.go
- Implement WaitGroup and goroutine function isolation
-
> chore: Solve Checkmarx race condition alert

- .github/workflows/tag-release.yml
- trigger build on tags such as x.y.z-something
-
> chore: Add build trigger glob pattern for version with suffix

- .github/pull-request-template.md
- .github/workflows/pr-github-checks.yml
- automate the label check in PRs
-
> chore: Add label check to gha

- receiver/kymastatsreceiver/config.go
- receiver/kymastatsreceiver/factory.go
- Remove unneeded k8s and unify `getDynamicClient` with `getDiscoveryClient`
-
> chore: Improve method name

- receiver/kymastatsreceiver/README.md
- receiver/kymastatsreceiver/config.go
- receiver/kymastatsreceiver/config_test.go
- receiver/kymastatsreceiver/factory.go
- receiver/kymastatsreceiver/internal/modulediscovery/client.go
- receiver/kymastatsreceiver/internal/modulediscovery/client_test.go
- receiver/kymastatsreceiver/kyma_scraper.go
- Implement resource exclusion
- Adjust log level
- Fix config example
- https://github.com/kyma-project/opentelemetry-collector-components/issues/90
> feat: Resource exclude list in kymastatsreceiver

- receiver/kymastatsreceiver/README.md
- Remove `excluded_resources` since this field was removed in https://github.com/kyma-project/opentelemetry-collector-components/pull/97
-
> docs: Fix kymastatsreceiver config example

- .github/workflows/pr-build-image.yaml
- .github/workflows/pr-code-checks.yml
- .github/workflows/pr-docu-checks.yml
- .github/workflows/pr-github-checks.yml
- introduce jobs to be used as repo rule checks
> chore: Prepare for repo-rules

- receiver/kymastatsreceiver/internal/metadata/generated_metrics.go
- receiver/kymastatsreceiver/internal/metadata/generated_status.go
- receiver/kymastatsreceiver/metadata.yaml
- receiver/kymastatsreceiver/testdata/metrics.yaml
- receiver/singletonreceivercreator/internal/metadata/generated_status.go
- receiver/singletonreceivercreator/internal/metadata/generated_telemetry.go
- receiver/singletonreceivercreator/internal/metadata/generated_telemetry_test.go
- receiver/singletonreceivercreator/metadata.yaml
- Remove custom scope names to comply with the change made in OTel Collector 0.107.0: https://github.com/open-telemetry/opentelemetry-collector/issues/9494
-
> feat: Update scope names to comply with the new convention

- .github/workflows/pr-code-checks.yml
- Replaced workflow path filter with changed-files
- Fixed workflow name
- https://github.com/kyma-project/telemetry-manager/pull/1382
- https://github.com/kyma-project/telemetry-manager/pull/1383
> chore: Replace workflow path filter with changed-files

- docs/contributor/releasing.md
-  Deleted the steps as it was confusing
-
> docs: Update release process

- otel-collector/builder-config.yaml
- Add `routingconnector` and `forwardconnector` components to our custom collector image
- kyma-project/telemetry-manager#1300
> feat: Add connectors to collector image

- .github/dependabot.yml
- include all changes from otel-collector-contrib in the otel dependabot group
-
> chore: Widen pattern for dependabot grouping

- .github/dependabot.yml
- group all otel cahnges, previously exporters/extension ... were not grouped in here
-
> chore: Group all otel changes regardless of their subdirectory

- renovate.json
> chore: Enable go mod tidy as post update in renovate

- renovate.json
> chore: Skip digest updates for go

- .github/workflows/pr-github-checks.yml
- .github/workflows/titleprefix_to_label.json
- renovate.json
- enable setting milestone and labels automatically
- synchronize renovate configuration with other repositories
-
> chore: Enable label and milestone automation

- cmd/otelkymacol/go.mod
- cmd/otelkymacol/go.sum
- internal/k8sconfig/go.mod
- internal/k8sconfig/go.sum
- receiver/kymastatsreceiver/go.mod
- receiver/kymastatsreceiver/go.sum
- receiver/singletonreceivercreator/go.mod
- receiver/singletonreceivercreator/go.sum
> chore: Bump x/oauth2 dependency

- .github/workflows/pr-build-image.yaml
- .github/workflows/tag-release.yml
> chore: add additional permissions for image builder

- .github/workflows/tag-release.yml
> chore: request permissions needed for creating a release

- .github/workflows/pr-build-image.yaml
- .github/workflows/pr-code-checks.yml
- .github/workflows/pr-docu-checks.yml
- Removed the action fully and replaced with regular paths-ignore
- Added ignore patterns to other workflows as well
-
> chore: remove GH action tj-action

- .github/workflows/pr-all-checks-passed.yml
- .github/workflows/pr-github-checks.yml
- renovate.json
- update gh action to proper release versions
-
> chore: update gh action to proper release versions

- .github/workflows/create-release.yaml
- .github/workflows/periodic-github-checks.yaml
- .github/workflows/pr-all-checks-passed.yml
- .github/workflows/pr-build-image.yaml
- .github/workflows/pr-code-checks.yml
- .github/workflows/pr-docu-checks.yml
- .github/workflows/pr-github-checks.yml
- CodeQL reports that default permissions are to corse-grained
- -> added most restrictive permissions for all jobs
- -> enabled more powerful permissions on the jobs directly
-
> chore: configure permissions for all gh actions

- .github/workflows/create-release.yaml
- .github/workflows/pr-build-image.yaml
- otel-collector/Dockerfile
- Add cross-compilation support
- Default to ARM and AMD architectures for image builds
- https://github.com/kyma-project/telemetry-manager/issues/2167
> feat: support ARM architectures

- otel-collector/builder-config.yaml
- Add missing `istio_enrichment` processor
-
> fix: add missing processor
